import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'
import PlayerCard from './PlayerCard/PlayerCard';

export default function Home() {

  const [players, setPlayers] = useState([]);
  const [teams, setTeams] = useState([]);

  useEffect(()=>{
    fetchPlayerData();
    fetchTeamData();
  }, [])

  const fetchPlayerData = () => {
    fetch("api/players", {
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
    })
      .then((response) => {
        return response.json();
      })
      .then((json) => {
        setPlayers(json);
      });
  }

  const fetchTeamData = () => {
    fetch("api/teams", {
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
    })
      .then((response) => {
        return response.json();
      })
      .then((json) => {
        setTeams(json);
      });
  }
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
        teams && players && 
          <>
            <h1>Players</h1>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 md:gap-x-10 xl-grid-cols-4 gap-y-10 gap-x-6">
              {players.slice(0, 10).map(x => <PlayerCard key={x.slug} team={teams.filter(team => team.ta === x.ta)[0]} {...x} />)}
            </div>
            <h1>Teams</h1>
          </>
      }

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
